apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dz6cmc345-nodejs-gitops
  description: This is GitOps manifest for dz6cmc345-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=dz6cmc345-nodejs
    backstage.io/kubernetes-id: dz6cmc345-nodejs 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-qe-jsmid/dz6cmc345-nodejs-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:dz6cmc345-nodejs
